// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACblBsWuCzjAs8dMNAREJeSroTM3hCqx0',
    appId: '1:1048317509791:web:81cdc7925936b79bf062aa',
    messagingSenderId: '1048317509791',
    projectId: 'referral-app-flut',
    authDomain: 'referral-app-flut.firebaseapp.com',
    storageBucket: 'referral-app-flut.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECdRlIHDEfMnvVB90gTTsmxlRo1V-EFI',
    appId: '1:1048317509791:android:4a059f2629cd54a2f062aa',
    messagingSenderId: '1048317509791',
    projectId: 'referral-app-flut',
    storageBucket: 'referral-app-flut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9guAq02fmr_kwSIWWFqhfH4WYIPWiKxg',
    appId: '1:1048317509791:ios:f518ceb223b236bcf062aa',
    messagingSenderId: '1048317509791',
    projectId: 'referral-app-flut',
    storageBucket: 'referral-app-flut.appspot.com',
    iosBundleId: 'com.example.flutterReferralApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9guAq02fmr_kwSIWWFqhfH4WYIPWiKxg',
    appId: '1:1048317509791:ios:804bfaad42460471f062aa',
    messagingSenderId: '1048317509791',
    projectId: 'referral-app-flut',
    storageBucket: 'referral-app-flut.appspot.com',
    iosBundleId: 'com.example.flutterReferralApp.RunnerTests',
  );
}
